# DeepSomatic Pipeline Configuration
# ====================================

output_dir: "deepsomatic_output/"

# Input Files (path/to/file.ext)
# -----------
tumor_bam: "downsampled/tumor.bam"
normal_bam: "downsampled/normal.bam"  
reference: "deepsomatic_data/reference.fa"
ground_truth_vcf: "deepsomatic_data/truth.vcf.gz"


# Optional Parameters
# -------------------
# Number of parallel shards (default: 2)
# Note: Use fewer shards for small regions to avoid segmentation faults
num_shards: 2

# Uncomment and set to analyze specific genomic regions
# Example: "chr17:7670000-7680000"
regions: "chr17:7670000-7680000"
